version: '3.4'
services:
  redis:
    env_file:
      - ".env"
    image: "redis:5.0.4-stretch"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD}"
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - "redis:/data"

  rabbit_mq:
    env_file:
      - ".env"
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD}"
    depends_on:
      - "redis"
    ports:
      - 5672:5672
      - 8080:15672
    expose:
      - 5672
      - 8080
    volumes:
      - "rabbit_mq:/var/lib/rabbitmq"

  web:
    network_mode: host
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - ".env"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      RABBIT_MQ_URL: ${RABBIT_MQ_URL}
    depends_on:
      - "rabbit_mq"
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - "app_logs:/logs"

  worker-add:
    network_mode: host
    build:
      context: "."
    command: /usr/bin/supervisord -c supervisord_add.conf
    depends_on:
      - "web"
    env_file:
      - ".env"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "./logs:/logs"

  worker-divide:
    network_mode: host
    build:
      context: "."
    command: /usr/bin/supervisord -c supervisord_divide.conf
    depends_on:
      - "web"
    env_file:
      - ".env"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "./logs:/logs"

  flower:
    network_mode: host
    image: mher/flower:0.9.5
    depends_on:
      - "web"
    environment:
      - CELERY_ENABLE_UTC=False
      - CELERY_TIMEZONE=Africa/Nairobi
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672//
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    expose:
      - 8888
    volumes:
      - "flower:/data/celery-worker.py"

volumes:
  redis: {}
  rabbit_mq: {}
  app_logs: {}
  worker_logs: {}
  flower: {}