FROM python:3.7

#ENV VIRTUAL_ENV=/.env
#ENV PATH="$VIRTUAL_ENV/bin:$PATH"


WORKDIR /app

COPY ./shared/Pipfile ./shared/Pipfile.lock /app/

RUN ls /app

RUN apt-get update && \
  apt-get install supervisor -y && \
  pip install 'pipenv==2018.11.26' && \
  pipenv install --system --deploy --ignore-pipfile && \
  apt-get remove -y gcc python3-dev libssl-dev && \
  apt-get autoremove -y && \
  pip uninstall pipenv -y

#RUN pip install pipenv && \
#  apt-get update && \
#  apt-get install -y --no-install-recommends gcc python3-dev libssl-dev && \
#  PIPENV_DONT_LOAD_ENV=1 pipenv install --deploy --system && \
#  apt-get remove -y gcc python3-dev libssl-dev && \
#  apt-get autoremove -y && \
#  pip uninstall pipenv -y

#RUN ls /.env

RUN pip freeze

